#!/bin/sh
uci -q batch <<-EOF
    set oplist.main=oplist
    set oplist.main.enabled=0
    set oplist.main.port=5244
    set oplist.main.tls_enabled=0
    set oplist.main.log_enable=1
    set oplist.main.temp_dir=/etc/openlist/temp
    commit oplist
EOF
exit 0