name : I only smoke when i drink

on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Build for ${{ matrix.patch_arch }}
    runs-on: ubuntu-latest
    env:
      project_name: "luci-app-oplist"
      openlist_version: "4.2.2"
    strategy:
      fail-fast: false
      matrix:
        include:
          - openlist_arch: "amd64"
            patch_arch: "x86_64"
            sdk_name: "openwrt-sdk-25.12.4-x86-64_gcc-14.3.0_musl.Linux-x86_64"
          - openlist_arch: "arm64"
            patch_arch: "aarch64_generic"
            sdk_name: "openwrt-sdk-25.12.4-rockchip-armv8_gcc-14.3.0_musl.Linux-x86_64"

    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Install Build Dependencies
        uses: mokanove/mokanove/actions/luci-env@main

      - name: Prepare SDK
        uses: mokanove/mokanove/actions/prepare-sdk@main
        with:
          sdk_name: ${{ matrix.sdk_name }}

      - name: Clone Source Code
        uses: mokanove/mokanove/actions/clone@main
        with:
          sdk_name: ${{ matrix.sdk_name }}
          project_name: ${{ env.project_name }}

      - name: Get Version
        id: get_version
        shell: bash
        run: |
          cd ${{ matrix.sdk_name }}/package/${{ env.project_name }}
          VERSION=$(grep -E "^PKG_VERSION[[:space:]]*:=" Makefile | sed -E 's/.*:=[[:space:]]*//' | tr -d '[:space:]')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Change Arch
        shell: bash
        run: |
          cd ${{ matrix.sdk_name }}/package/${{ env.project_name }}
          if [ "${{ matrix.patch_arch }}" != "x86_64" ]; then
            sed -i 's/x86_64/${{ matrix.patch_arch }}/g' ./Makefile
          fi

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: '26.2.0'
          cache: true

      - name: Set up pnpm
        uses: pnpm/action-setup@master
        with:
          version: '11.5'
          cache: true

      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: '1.26.3'
          cache: true

      - name: Build OpenList Front-End
        shell: bash
        run: |
          git clone --depth 1 https://github.com/OpenListTeam/OpenList-Frontend.git frontend-src
          cd frontend-src
          pnpm install
          pnpm build

      - name: Build OpenList Binary
        shell: bash
        run: |
          git clone --depth 1 https://github.com/OpenListTeam/OpenList.git backend-src

          cd backend-src
          bash build.sh dev web

          builtAt="$(date +'%F %T %z')"
          goVersion=$(go version | sed 's/go version //')
          gitAuthor=$(git show -s --format='format:%aN <%ae>' HEAD)
          gitCommit=$(git log --pretty=format:"%h" -1)
          version=$(git describe --long --tags --dirty --always)

          webVersion=$(curl -s --max-time 5 "https://api.github.com/repos/OpenListTeam/OpenList-Frontend/releases/latest" -L | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | sed 's/^v//')
          if [ -z "$webVersion" ]; then
              webVersion="${{ steps.get_version.outputs.version }}"
          fi

          ldflags="-w -s \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.BuiltAt=$builtAt' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.GoVersion=$goVersion' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.GitAuthor=$gitAuthor' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.GitCommit=$gitCommit' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.Version=$version' \
            -X 'github.com/OpenListTeam/OpenList/v4/internal/conf.WebVersion=$webVersion'"
          GOOS=linux GOARCH=${{ matrix.openlist_arch }} CGO_ENABLED=0 go build -ldflags "$ldflags" -o openlist .

          chmod +x openlist
          mv ./openlist "$GITHUB_WORKSPACE/openlist"

      - name: Preparation before compilation
        shell: bash
        run: |
          cd ${{ matrix.sdk_name }}/package/${{ env.project_name }}/root/usr/bin/
          rm -f DONOTREMOVE
          mv "$GITHUB_WORKSPACE/openlist" ./
          cd ../../etc/openlist
          rm DONOTREMOVE

      - name: Build!
        uses: mokanove/mokanove/actions/build@main
        with:
          sdk_name: ${{ matrix.sdk_name }}
          project_name: ${{ env.project_name }}

      - name: Rename compilation files
        shell: bash
        run: |
          cd ${{ matrix.sdk_name }}/bin/packages/*/base/
          mv luci-app-oplist* luci-app-oplist-${{ steps.get_version.outputs.version }}-${{ matrix.patch_arch }}.apk

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: V${{ steps.get_version.outputs.version }}
          files: ${{ matrix.sdk_name }}/bin/packages/**/*.apk
          body: |
            # 📝 Release Notes
            - Upgrade pnpm version to 11.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
