name : Let's build from here

on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    name: Build (${{ matrix.version }}-${{ matrix.openlist_arch }}_${{ matrix.ext }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: "24.10.5"
            target: "x86"
            subtarget: "64"
            openlist_arch: "amd64"
            sdk_name: "immortalwrt-sdk-24.10.5-x86-64_gcc-13.3.0_musl.Linux-x86_64"
            ext: "ipk"
            needs_patch: false
          - version: "25.12-SNAPSHOT"
            target: "x86"
            subtarget: "64"
            openlist_arch: "amd64"
            sdk_name: "immortalwrt-sdk-25.12-SNAPSHOT-x86-64_gcc-14.3.0_musl.Linux-x86_64"
            ext: "apk"
            needs_patch: false
          - version: "25.12-SNAPSHOT"
            target: "rockchip"
            subtarget: "armv8"
            openlist_arch: "arm64"
            sdk_name: "immortalwrt-sdk-25.12-SNAPSHOT-rockchip-armv8_gcc-14.3.0_musl.Linux-x86_64"
            ext: "apk"
            needs_patch: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Install Build Dependencies
        uses: mokanove/mokanove/actions/luci-env@main

      - name: Prepare SDK
        uses: mokanove/mokanove/actions/prepare-sdk@main
        with:
          version: ${{ matrix.version }}
          target: ${{ matrix.target }}
          subtarget: ${{ matrix.subtarget }}
          sdk_name: ${{ matrix.sdk_name }}

      - name: Clone Project source code & Get Version & Change Arch
        id: get_version
        run: |
          cd ${{ matrix.sdk_name }}/package/
          git clone https://github.com/mokanove/luci-app-oplist.git
          cd luci-app-oplist/
          VERSION=$(grep -E "^PKG_VERSION[[:space:]]*:=" Makefile | sed -E 's/.*:=[[:space:]]*//' | tr -d '[:space:]')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          if [ "${{ matrix.needs_patch }}" == "true" ]; then
            sleep 100
            sed -i 's/x86_64/aarch64_generic/g' Makefile
          fi
          cd root/usr/bin/
          rm DONOTREMOVE
          curl -LO "https://github.com/OpenListTeam/OpenList/releases/download/v4.1.10/openlist-linux-musl-${{ matrix.openlist_arch }}.tar.gz"
          tar -xzvf *.tar.gz
          rm -f *.tar.gz DONOTREMOVE
          cd ../../etc/openlist
          rm DONOTREMOVE

      - name: Build!
        run: |
          cd ${{ matrix.sdk_name }}
          make package/luci-app-oplist/compile V=s -j$(nproc)

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: V${{ steps.get_version.outputs.version }}
          files: |
              ${{ matrix.sdk_name }}/bin/packages/*/base/*.${{ matrix.ext }}
          body: |
            # This release by GitHub Actions
            > If it works, then that's correct.
            ## Please note:
            > APK files do not specify the architecture in their filenames.
            >
            > Therefore, please refer to the timestamps; the later timestamps are for X86_64 devices, and the earlier timestamps are for aarch64_rockchip devices.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
